name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify Render to deploy
      env:
        #RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_API_KEY: 'rnd_p6UDQhliszIevEDkvI4WhxHO2u3R'
        RENDER_SERVICE_ID: 'srv-ct9shkd6l47c73beh1gg'
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{env.RENDER_API_KEY}}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "'"${{ env.RENDER_SERVICE_ID }}"'", "clearCache": false}' \
          https://api.render.com/v1/services/${{ env.RENDER_SERVICE_ID }}/deploys
