name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Data Backend to Render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/master'
        env:
         # deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
         deploy_url : https://api.render.com/deploy/srv-ct9shkd6l47c73beh1gg?key=v7xCCuUa_Z0
        run: |
          curl "$deploy_url"
      

      - name: Deploy Auth Backend to Render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/master'
        env:
         # deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
         deploy_url : https://api.render.com/deploy/srv-cti7lhdds78s73c19cc0?key=FwFpmZB0mb4
        run: |
          curl "$deploy_url"
